# Generated by Django 6.0.3 on 2026-03-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('biblioteca', '0001_initial'), ('biblioteca', '0002_libro_anio_publicacion')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('anio_publicacion', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
