# Generated by Django 6.0.3 on 2026-03-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anio_publicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
