# Generated by Django 6.0.3 on 2026-03-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial_squashed_0002_libro_anio_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
